### ISSUE TITLE
设置自动开奖的用户只限于超级用户/SUPERUSER吗？

### ISSUE THREAD

**Issue by Judp28** [fluoresce0/zhenxun_plugins_luckyball#3]
能否把设置自动开奖的用户权限放宽到群管理员，或者添加一个超级用户通过私聊真寻就能设置所有群组的自动开奖时间的指令？比如私聊 定时幸运球设置18:00 [group_id] 即可完成设置

**Comment by fluoresce0** [comment]
> 能否把设置自动开奖的用户权限放宽到群管理员，或者添加一个超级用户通过私聊真寻就能设置所有群组的自动开奖时间的指令？比如私聊 定时幸运球设置18:00 [group_id] 即可完成设置
设为权限用户可以使用比较简单，修改代码以下位置即可
from models.level_user import LevelUser #加上这行
......
if cmdarg := args.extract_plain_text():
        level = await LevelUser.get_user_level(event.user_id, event.group_id)  #加上这3行
        if level < 5:
            await kj_matcher.finish("权限不足")
......

私聊group_id设置的话有点麻烦暂时不想写（

**Comment by Judp28** [comment]
这个幸运球在没有任何设置的情况下有默认的开奖时间吗

**Comment by Judp28** [comment]
> 这个幸运球在没有任何设置的情况下有默认的开奖时间吗

我翻了一下代码，似乎没有

**Comment by fluoresce0** [comment]
> 

考虑到并不是所有群都需要这个功能，同时避免同一时间往多群发消息的风险。所以没有默认的开奖时间，需要自行定时幸运球设置
